POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "A Rock Solid, Modern Web Stack—Rails 5 API + ActiveAdmin + Create React App on Heroku",
  "author": "CHARLIE GLEASON",
  "url": "https://blog.heroku.com/a-rock-solid-modern-web-stack",
  "likes": 1036
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "Ruby on Rails vs Node.js – The Right Approach To Web Development",
  "author": "Dawid Karczewski",
  "url": "https://www.ideamotive.co/blog/ruby-on-rails-vs-node-js",
  "likes": 1886
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "Building the DOM faster: speculative parsing, async, defer and preload",
  "author": "Milica Mihajlija",
  "url": "https://hacks.mozilla.org/2017/09/building-the-dom-faster-speculative-parsing-async-defer-and-preload/",
  "likes": 343
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "Things I Don’t Know as of 2018",
  "author": "Dan Abramov",
  "url": "https://overreacted.io/things-i-dont-know-as-of-2018/",
  "likes": 993
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "Writing Resilient Components",
  "author": "Dan Abramov",
  "url": "https://overreacted.io/writing-resilient-components/",
  "likes": 560
}